services:
  api:
    build:
      context: .
    container_name: api
    image: api_image:latest
    working_dir: /app
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres
    command: postgres -c 'max_connections=200'
    container_name: db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: student
      POSTGRES_PASSWORD: HjjnGytfnhg

  pg:
    image: dpage/pgadmin4:8.9
    container_name: pg
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=student@npi-tu.ru
      - PGADMIN_DEFAULT_PASSWORD=TlBJREVQUE9WVA==
    ports:
      - '7777:80'